version: "3"

services:
  db:
    image: mysql:5.7
    container_name: db
    env_file:
      - .env
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  django:
    build:
      context: .
    container_name: web
    env_file:
    - .env
    command: python src/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  my-db:
